# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190610_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='article_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='articles'),
            preserve_default=False,
        ),
    ]
